# Generated by Django 6.0.6 on 2026-06-24 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام ')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='نام کاربری')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='عکس پروفایل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='محل سکونت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
