# Generated by Django 6.0.6 on 2026-06-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favoriteslist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteslist',
            old_name='item_list',
            new_name='product',
        ),
    ]
