# Generated by Django 6.0.6 on 2026-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favoriteslist', '0002_rename_item_list_favoriteslist_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Favoriteslist',
        ),
    ]
