# Generated by Django 6.0.6 on 2026-06-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favoriteslist', '0003_product_delete_favoriteslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
    ]
