# Generated by Django 6.0.6 on 2026-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
